language: java

jdk:
  - openjdk11

jobs:
  include:
    - stage: deploy
      jdk: openjdk11
      script: skip
      deploy:
        - provider: releases
          edge: true
          file_glob: true
          file: build/libs/*
          draft: true
          on:
            tags: true
